name: Update Dependancy Graph

on: [push]

jobs:
  dependency-graph:
    runs-on: ubuntu-latest
    steps:
    - name: Submit Dependency Snapshot
      uses: advanced-security/maven-dependency-submission-action@v4
